axon:
  max_gradients: 100
  max_workers: 10
  port: 8091
  remote_ip: 99.238.136.56
dendrite:
  do_backoff: true
  key_dim: 100
  max_backoff: 100
  pass_gradients: true
  stale_emit_filter: 10000
  timeout: 0.5
  topk: 10
metagraph:
  chain_endpoint: feynman.kusanagi.bittensor.com:9944
  stale_emit_filter: 10000
neuron:
  accumulation_interval: 5
  apply_remote_gradients: true
  batch_size_train: 4
  datapath: data
  learning_rate: 0.00002
  log_interval: 10
  momentum: 0.98
  name: Adam
  sync_interval: 200
  trial_id: '1608300539'
  trial_path: data/adam/1608300539
  record_log: true
nucleus:
  max_workers: 5
  queue_maxsize: 10
  queue_timeout: 5
session:
  coldkeyfile: ~/.bittensor/coldkey
  hotkeyfile: ~/.bittensor/hotkey
  keypair: '5DaQQ6umBFmZRmj5pDPK1oXz6NWWRGjngBJozLFQJSM3PAP8'
synapse:
  activation_function: gelu_new
  attn_pdrop: 0.1
  embd_pdrop: 0.1
  initializer_range: 0.02
  layer_norm_epsilon: 1.0e-05
  n_head: 16
  n_inner: null
  n_layer: 12
  resid_pdrop: 0.1
  summary_activation: null
  summary_first_dropout: 0.1
  summary_proj_to_labels: true
  summary_type: cls_index
  summary_use_proj: true