version: "3.2"

services:
  dev:
    container_name: node-bittensor
    image: "bittensor/bittensor:latest"
    ports:
      - "8091:8091"
    volumes:
      - ~/.bittensor:/root/.bittensor
    
    command: /bin/bash -c "
      cd /bittensor
      && python3.7 examples/TEXT/gpt2_genesis.py --metagraph.chain_endpoint 172.17.0.1:9944"
